export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div>
        <h1>
          Meta<span>Bog</span>
        </h1>{" "}
        <div>
          <button>Home</button>
          <button>Blog</button>
          <button>Contact</button>
        </div>
        <div>
          <textarea></textarea>
          <button></button>
        </div>
      </div>
      <body>{children}</body>
    </html>
  );
}
