export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <div className="flex flex-row justify-normal">
        <h1>
          Meta<span>Bog</span>
        </h1>{" "}
        <div className="flex flex-row">
          <button>Home</button>
          <button>Blog</button>
          <button>Contact</button>
        </div>
        <div className="flex flex-row">
          <textarea></textarea>
          <button>P</button>
        </div>
      </div>
      <body>{children}</body>
    </html>
  );
}
